name: audioplayer
description: A flutter plugin to play audio files
version: 0.5.3
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/audioplayer

flutter:
  plugin:
    androidPackage: bz.rxla.audioplayer
    pluginClass: AudioplayerPlugin

dependencies:
  flutter:
    sdk: flutter
  logging: ^ 0.11.3+2

environment:
  sdk: ">=1.19.0 <3.0.0"
